### ISSUE TITLE
Update `business-partner-validation` documentation

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-tractusx/tractusx-edc#611] opened 2023-07-13 11:46 UTC
## Describe the bug

The documentation (e.g. [README.md](https://github.com/eclipse-tractusx/tractusx-edc/tree/main/edc-extensions/business-partner-validation/README.md)) of the `business-partner-validation` extension is outdated.

### Expected behavior

It should be always in sync with the real implementations!

**Comment by ndr-brt** [comment] 2023-07-13 15:22
Definitely not a bug, maybe the README could be less detailed about the json format and only specify what's the `leftOperand` name that's used for the validation, with a link to the ODRL documentation.

**Comment by paullatzelsperger** [comment] 2023-07-19 06:02
on a broader scope, the `business-partner-validation` is based on a fundamentally flawed design, as it hard-codes the BPNs into the policy, which means the policy must be updated everytime an asset should be shared with a new participant.

I don't disagree that documentation should be up-to-date, but maybe a larger refactoring is in order here?

**Comment by saschaisele-zf** [comment] 2023-10-18 06:18
Since the [bpn-validation](https://github.com/eclipse-tractusx/tractusx-edc/tree/main/edc-extensions/bpn-validation) extension was reworked and is properly documented, I would close this issue.

**Closed** 2023-10-18 06:29 UTC
Labels: documentation
